// Fill out your copyright notice in the Description page of Project Settings.


#include "SpartaGameState.h"
#include "Kismet/GameplayStatics.h"
#include "SpawnVolume.h"
#include "CoinItem.h"
#include "SpartaPlayerController.h"
#include "SpartaCharacter.h"
#include "SpartaGameInstance.h"
#include "Components/TextBlock.h"
#include "Blueprint/UserWidget.h"

ASpartaGameState::ASpartaGameState()
{
	Score = 0;
	SpawnedCoinCount = 0;
	CollectedCoinCount = 0;
	LevelDuration = 30.0f;
	CurrentLevelIndex = 0;
	MaxLevel = 3;

	CurrentWaveIndex = 0;
	MaxWaveIndex = 3;       // ğŸ’¡ ì›¨ì´ë¸Œ 3ê°œ
	WaveDuration = 10.0f;   // ğŸ’¡ ê° ì›¨ì´ë¸Œ 10ì´ˆ
}

void ASpartaGameState::BeginPlay()
{
	Super::BeginPlay();

	StartLevel();

	GetWorldTimerManager().SetTimer(
		HUDUpdataTimerHandle, 
		this, 
		&ASpartaGameState::UpdateHUD, 
		0.1f, 
		true // true means it will repeat every second
	);
}

int32 ASpartaGameState::GetScore() const
{
	return Score;
}

void ASpartaGameState::AddScore(int32 Amount)
{
	if(UGameInstance* GameInstance = GetGameInstance())
	{
		USpartaGameInstance* SpartaGameInstance = Cast<USpartaGameInstance>(GameInstance);
		if(SpartaGameInstance)
		{
			SpartaGameInstance->AddToScore(Amount);
		}
	}
}

void ASpartaGameState::StartLevel()
{
	if(APlayerController* PlayerController = GetWorld()->GetFirstPlayerController()) //ê²Œì„ ìŠ¤íƒ€íŠ¸ ì‹œ ë©”ë‰´ UI ì¢…ë£Œ í›„ HUD í‘œì‹œ
	{
		if(ASpartaPlayerController* SpartaPlayerController = Cast<ASpartaPlayerController>(PlayerController))
		{
			SpartaPlayerController->ShowGameHUD(); //ê²Œì„ HUD í‘œì‹œ
		}
	}


	if ( UGameInstance* GameInstance = GetGameInstance() )
	{
		USpartaGameInstance* SpartaGameInstance = Cast<USpartaGameInstance>(GameInstance);
		if ( SpartaGameInstance )
		{
			CurrentLevelIndex = SpartaGameInstance->CurrentLevelIndex;
		}
	}

	CurrentWaveIndex = 0; // ì›¨ì´ë¸Œ ì´ˆê¸°í™”
	StartWave(); // ì²« ë²ˆì§¸ ì›¨ì´ë¸Œ ì‹œì‘

	/*
	SpawnedCoinCount = 0;
	CollectedCoinCount = 0;

	TArray<AActor*> FoundVolumes;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASpawnVolume::StaticClass(), FoundVolumes);

	const int32 ItemToSpawn = 40; // ì•„ì´í…œ 40ê°œ ìŠ¤í°

	for(int32 i = 0; i < ItemToSpawn; i++)
	{
		if (FoundVolumes.Num() > 0)
		{
			int32 RandomIndex = FMath::RandRange(0, FoundVolumes.Num() - 1);
			ASpawnVolume* SpawnVolume = Cast<ASpawnVolume>(FoundVolumes[RandomIndex]);
			if (SpawnVolume)
			{
				AActor* SpawnedActor = SpawnVolume->SpawnRandomItem();
				if(SpawnedActor &&  SpawnedActor->IsA(ACoinItem::StaticClass()) )

				SpawnedCoinCount++;
			}
		}
	}

	GetWorldTimerManager().SetTimer(
		LevelTimerHandle, 
		this, 
		&ASpartaGameState::OnLevelTimeUp, 
		LevelDuration, 
		false // false means it will not repeat
	);
	UE_LOG(LogTemp, Warning, TEXT("Level %d Start!, Spawned %d coins"), CurrentLevelIndex + 1, SpawnedCoinCount);
	GEngine->AddOnScreenDebugMessage(-1,
		2.0f,
		FColor::Orange,
		FString::Printf(TEXT("ë ˆë²¨ %d Start!, %d ê°œ ì½”ì¸ ìƒì„±!"), CurrentLevelIndex + 1, SpawnedCoinCount));
		*/
	
}

void ASpartaGameState::OnLevelTimeUp()
{
	EndLevel();
}

void ASpartaGameState::OnCoinCollected()
{
	CollectedCoinCount++;
	/*UE_LOG(LogTemp, Warning, TEXT("Coin Collected: %d / %d"), CollectedCoinCount, SpawnedCoinCount);
	GEngine->AddOnScreenDebugMessage(-1,
		2.0f,
		FColor::Orange,
		FString::Printf(TEXT("ë‚¨ì€ ì½”ì¸: %d / %d"), CollectedCoinCount, SpawnedCoinCount));*/

	if(SpawnedCoinCount > 0 && CollectedCoinCount >= SpawnedCoinCount)
	{
		//EndLevel();
		GetWorldTimerManager().ClearTimer(LevelTimerHandle);
		OnWaveTimeUp();
	}
}

void ASpartaGameState::EndLevel()
{
	GetWorldTimerManager().ClearTimer(LevelTimerHandle);

	if ( UGameInstance* GameInstance = GetGameInstance() )
	{
		USpartaGameInstance* SpartaGameInstance = Cast<USpartaGameInstance>(GameInstance);
		if ( SpartaGameInstance )
		{
			AddScore(Score);
			CurrentLevelIndex++;
			SpartaGameInstance->CurrentLevelIndex = CurrentLevelIndex;
		}
	}

	if ( CurrentLevelIndex >= MaxLevel )
	{
		OnGameOver();
		return;
	}
	
	if(LevelMapNames.IsValidIndex(CurrentLevelIndex))
	{
		//FName NextLevelName = LevelMapNames[CurrentLevelIndex];
		//UGameplayStatics::OpenLevel(this, NextLevelName);
		GetWorldTimerManager().ClearTimer(LevelTimerHandle);
		UGameplayStatics::OpenLevel(GetWorld(), LevelMapNames[CurrentLevelIndex]);
	}
	else
	{
		OnGameOver();
	}
}

void ASpartaGameState::OnGameOver()
{
	if ( APlayerController* PlayerController = GetWorld()->GetFirstPlayerController() ) //ê²Œì„ ìŠ¤íƒ€íŠ¸ ì‹œ ë©”ë‰´ UI ì¢…ë£Œ í›„ HUD í‘œì‹œ
	{
		if ( ASpartaPlayerController* SpartaPlayerController = Cast<ASpartaPlayerController>(PlayerController) )
		{
			SpartaPlayerController->SetPause(true); //ê²Œì„ ì¼ì‹œì •ì§€
			SpartaPlayerController->bIsRestart = true; //ê²Œì„ ì¬ì‹œì‘ ì—¬ë¶€ ì„¤ì •
			SpartaPlayerController->ShowMainMenu(SpartaPlayerController->bIsRestart); //ê²Œì„ HUD í‘œì‹œ
		}
	}

	if ( UGameInstance* GameInstance = GetGameInstance() )
	{
		USpartaGameInstance* SpartaGameInstance = Cast<USpartaGameInstance>(GameInstance);
		if ( SpartaGameInstance )
		{
			int32 TotalScore = SpartaGameInstance->TotalScore;
			/*UE_LOG(LogTemp, Warning, TEXT("Game Over! Final Score: %d"), TotalScore);
			GEngine->AddOnScreenDebugMessage(-1,
				2.0f,
				FColor::Orange,
				FString::Printf(TEXT("ê²Œì„ ì¢…ë£Œ! ì´í•© ì ìˆ˜: %d"), TotalScore));*/
		}
	}
	
}

void ASpartaGameState::UpdateHUD()
{
	if ( APlayerController* PlayerController = GetWorld()->GetFirstPlayerController() )
	{
		if ( ASpartaPlayerController* SpartaPlayerController = Cast<ASpartaPlayerController>(PlayerController) )
		{
			if ( UUserWidget* HUDWidget = SpartaPlayerController->GetHUDWidget() )
			{
				if ( UTextBlock* TimeText = Cast<UTextBlock>(HUDWidget->GetWidgetFromName(TEXT("Time"))) )
				{
					float RemainTime = GetWorldTimerManager().GetTimerRemaining(LevelTimerHandle);
					TimeText->SetText(FText::FromString(FString::Printf(TEXT("Time: %.1f"), RemainTime)));
				}
				if ( UTextBlock* ScoreText = Cast<UTextBlock>(HUDWidget->GetWidgetFromName(TEXT("Score"))) )
				{
					if(UGameInstance* GameInstance = GetGameInstance())
					{
						USpartaGameInstance* SpartaGameInstance = Cast<USpartaGameInstance>(GameInstance);
						if(SpartaGameInstance)
						{
							ScoreText->SetText(FText::FromString(FString::Printf(TEXT("Score: %d"), SpartaGameInstance->TotalScore)));
						}
					}
				}
				if ( UTextBlock* LevelIndexText = Cast<UTextBlock>(HUDWidget->GetWidgetFromName(TEXT("Level"))) )
				{
					LevelIndexText->SetText(FText::FromString(FString::Printf(TEXT("Level: %d (Wave: %d)"), CurrentLevelIndex + 1, CurrentWaveIndex + 1)));
				}
				if ( UTextBlock* HealthText = Cast<UTextBlock>(HUDWidget->GetWidgetFromName(TEXT("HP"))) )
				{
					if ( APlayerController* PC = GetWorld()->GetFirstPlayerController() )
					{
						if ( ASpartaCharacter* Player = Cast<ASpartaCharacter>(PC->GetPawn()) )
						{
							HealthText->SetText(FText::FromString(FString::Printf(TEXT("HP : %.0f"), Player->GetHealth())));
						}
					}
				}

			}
		}
	}
}

void ASpartaGameState::StartWave()
{
	SpawnedCoinCount = 0;
	CollectedCoinCount = 0;

	TArray<AActor*> ExistingItem;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ABaseItem::StaticClass(), ExistingItem);

	for ( AActor* Item : ExistingItem )
	{
		if (Item)
		{
			Item->Destroy();
		}
	}

	int32 ItemToSpawn = 30 + CurrentWaveIndex * 10; //ì›¨ì´ë¸Œ ë‹¹ ì•„ì´í…œ ìˆ˜ ì¦ê°€

	TArray<AActor*> FoundVolumes;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ASpawnVolume::StaticClass(), FoundVolumes);

	for ( int32 i = 0; i < ItemToSpawn; i++ )
	{
		if ( FoundVolumes.Num() > 0 )
		{
			int32 RandomIndex = FMath::RandRange(0, FoundVolumes.Num() - 1);
			ASpawnVolume* SpawnVolume = Cast<ASpawnVolume>(FoundVolumes[RandomIndex]);
			if ( SpawnVolume )
			{
				AActor* SpawnedActor = SpawnVolume->SpawnRandomItem();
				if ( SpawnedActor && SpawnedActor->IsA(ACoinItem::StaticClass()) )
				{
					SpawnedCoinCount++;
				}
			}
		}
	}
	GetWorldTimerManager().SetTimer(
		LevelTimerHandle,
		this,
		&ASpartaGameState::OnWaveTimeUp,
		WaveDuration,
		false // false means it will not repeat
	);


	UE_LOG(LogTemp, Warning, TEXT("Wave %d ì‹œì‘!"), CurrentWaveIndex + 1);
	GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Orange,
		FString::Printf(TEXT("Wave %d ì‹œì‘! ì´ %d ê°œ ì•„ì´í…œ ìƒì„±!"), CurrentWaveIndex + 1, SpawnedCoinCount));
}

void ASpartaGameState::OnWaveTimeUp()
{
	CurrentWaveIndex++;

	if ( CurrentWaveIndex >= MaxWaveIndex )
	{
		EndLevel(); // ë§ˆì§€ë§‰ ì›¨ì´ë¸Œ ì™„ë£Œ ì‹œ ë ˆë²¨ ì¢…ë£Œ
	}
	else
	{
		StartWave(); // ë‹¤ìŒ ì›¨ì´ë¸Œ ì‹œì‘
	}
}